### ISSUE TITLE
Vyper or something else

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/fe#13]
The python vyper compiler is continuing with development.

There are already choices in this codebase which make this version of vyper not syntactically compatible with the python one.  For this reason I think we have two choices.

1. engage with the python-vyper team to converge on a single language spec.
2. pick a new name.

No urgency if we're good with option 2 (even if we don't end up going that way).  More urgency if we want to put in the political work to converge the language syntax.

**Comment by davesque** [comment]
For some context, converging on the language syntax will probably mean that they have to write their own parser instead of depending on the python stdlib parser.  IMHO, reliance on the stdlib parser was one of the things holding the language back and even encouraging patterns of corner-cutting that led to bad engineering practices.  It would be great if the python vyper was willing to write a custom parser, but it might be a big ask.

**Comment by fubuloubu** [comment]
https://github.com/vyperlang/vyper/blob/master/tests/grammar/vyper.lark

**Comment by fubuloubu** [comment]
The eventual idea is that if it's good enough to pass test suite, it should be good enough to start on a refactor of the compiler front end. I would eventually like to move to Lark fully: https://github.com/fubuloubu/vyper-redux/blob/master/vyper/ast.py#L229 details an idea of how this might look

**Comment by fubuloubu** [comment]
One last comment: any attempt to redefine aspects of the language and it's syntax outside of the VIP process is not likely to be credibly engaging with the project, and is likely to miss important aspects of how the language is progressing and is actually being used. If you would rather write your own syntax, I highly suggest just changing the name of this project. It will be easier for you.
