### ISSUE TITLE
keccak256

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#188]
### What is wrong?

Users cannot perform `keccak256` on values (e.g. `my_num.keccak256()`).

### How can it be fixed

An attribute function `keccak256` should be implemented on all data types.

**Comment by cburgdorf** [comment]
I can see the convenience of being able to call `keccak256()` on any variable. But I think I'd prefer having it as a standalone function because:

1. Planning ahead, this may not be the only cryptographic function that we need (e.g. [see](https://docs.soliditylang.org/en/v0.4.21/units-and-global-variables.html#mathematical-and-cryptographic-functions))
2. In the future `keccak256` usage my start to decline leaving us with "API pollution"
3. We can start having `keccak256` globally available and eventually move it behind an import when we support them (e.g. `from crypto import keccak256`). This will be a less harsh breaking change compared to removing a builtin on all types.

In general, my stance is to be extra cautious with builtin methods that we provide on a broad set of types. I think that importing is generally more future proof and provides a cleaner way to evolve the language. I think that's also a general stance that the rust team uses as guidance.

**Comment by cburgdorf** [comment]
This landed with #255
