### ISSUE TITLE
Square root function

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#191]
### What is wrong?

There isn't a convenient way for a user to compute the square root of some value.

### How can it be fixed

We should provide some function for computing the square root.

**Comment by g-r-a-n-t** [comment]
Quick thought: it might make sense to implement this functionality in Fe as a contract function, instead of providing another builtin.

**Comment by cburgdorf** [comment]
I think it might make sense to implement it on number types. E.g. rust provides it on floating types. Having said that, I'm not sure how people regular deal with square roots in the EVM since it doesn't work on floating types. Looking at something like this:

https://github.com/Uniswap/uniswap-v2-core/blob/4dd59067c76dea4a0e8e4bfdda41877a6b16dedc/contracts/libraries/Math.sol#L11-L22

Do people just use that with values that are safe to return not require decimals (e.g. `sqrt(9)`). To me, it would make sense to push this feature back until we have proper imports and then one could bring it into scope via `from math import sqrt`. For the Uniswap demo we could include an ad hoc implementation as part of the Uniswap code (like Uniswap also does)

**Comment by cburgdorf** [comment]
Regarding floating point math. It seems solidity does have in fact [support for rational numbers](https://docs.soliditylang.org/en/develop/types.html#rational-and-integer-literals):

>Division on integer literals used to truncate in Solidity prior to version 0.4.0, but it now converts into a rational number, i.e. 5 / 2 is not equal to 2, but to 2.5.

So I assume something like `sqrt(2)` might in fact return `2.23606797749979` in solidity.

**Comment by cburgdorf** [comment]
Ah ok. And [Vyper supports a `decimal` type](https://vyper.readthedocs.io/en/latest/types.html?highlight=decimal#decimals) as well. So, I think this is where we should start: 

1. Add support for decimal
2. Make `sqrt` a function on `decimal` so that e.g `val.sqrt()` could be called assuming `val` is of type `decimal`

**Comment by cburgdorf** [comment]
Created an issue for decimal support https://github.com/ethereum/fe/issues/253

**Comment by cburgdorf** [comment]
Ok, for the record, the `sqrt` from Uniswap does operate on integer math so `sqrt(8)` returns `2` and `sqrt(16000)` returns `126`.

**Comment by g-r-a-n-t** [comment]
#259
