### ISSUE TITLE
Consider replacing Pythonic indents with curly braces

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#27]
**Warning**: This may turn out to be a controversial point, since it is about changing one of the core aspects of the syntax. While there seems to be some support from the people behind coq, and @g-r-a-n-t also said that he is open to this change, I am writing this topic to gauge the general sentiment and get the opinion of more people.

### Proposed Change

Currently contracts and functions follow the Pythonic indentation rules for their definition.

```
contract Something:
    pub def foo(from: address) -> address:
        return address
```

This issue proposes to use curly braces instead so the above syntax would become:

```
contract Something {
    pub def pass_through(from: address) -> address{
        return address
    }
}
```

### Motivation

The core motivation is that it becomes easier to parse and enables certain features down the road that would otherwise be hard to implement. For instance, the lack of curly braces is one of the main reasons why Python doesn't have rich support for lambdas.

Consider the following code.

```
contract Something {
    pub def pass_through(from: address) -> address{
        return self.things.filter(|thing| {
            if thing.address == address {
                return True
            } elif self.some_other_check(thing, address) {
                return True
            } else {
                return False
            }
        })
    }
}
```

Notice that I'm just artificially try to come up with a longer block inside the lambda to demonstrate something that isn't available in Python today.

Notice that I just went for the Rust lambda syntax but something like `filter(thing => {...})` (TypeScript syntax) would just work equally fine. It's out of the scope of this issue to discuss lambdas.

In my opinion, Rust as being a very young and modern language seems to have taken a lot of inspiration from Python but improved on the parts that turned out to be holding the language back. I feel that we should be following Rust in this aspect.

### Alternatives

My proposal above went into eliminating Pythonic indents all the way through contracts, functions, lamdbas as well as if / else because it felt like this change would naturally expand beyond just functions. However, we *could* also consider an alternative proposal that would just use curly braces for function bodies even though I have to admit it feels kind of weird.

 ```
contract Something:
    pub def pass_through(from: address) -> address{
        return self.things.filter(|thing| {
            if thing.address == address:
                return True
            elif self.some_other_check(thing, address):
                return True
            else:
                return False
        })
    }

```

**Comment by g-r-a-n-t** [comment]
The original proposal makes sense to me. So just to list them out, we would be modifying the [grammar](https://github.com/ethereum/fe/blob/master/parser/src/grammar/Vyper.grammar) of: `contract_def`, `func_def`, `if_stmt`, `elif_stmt`, `else_block`, `while_stmt`, and `for_stmt`.

@formalize would this change affect your work on the verified transformation?

**Comment by formalize** [comment]
No, it wont affect my work. Lambdas might affect it but currently I have no plans of supporting them. 

I support this proposal because parsing Python is less understood than it should be. Python spec describes the solution to the parsing problem (with all those IDENTs and DEDENTs) rather than the problem itself. 

In most languages the parsing problem goes like this: there are parse trees that can be unparsed into a string by concatenating all their leaves; to parse a string is to find a parse tree that unparses to that string. Now in Python some nodes of a parse tree would unparse by not just concatenating, but also adding indent to the unparsed form of their children. This is what should have gone into the Python spec, and IDENTs/DEDENTs would be just part of an algorithm that solves the Python parsing problem. And then somebody would have to verify a parser for that, of course.

And don't get me started on the question of whether one string of tabs and spaces is more of an indent than another such string. I believe that even Python itself does it wrong by checking only 1 and 8 as possible tab sizes whereas the spec says that all tab sizes should be considered.

**Comment by pipermerriam** [comment]
> For instance, the lack of curly braces is one of the main reasons why Python doesn't have rich support for lambdas.

@cburgdorf can you provide a citation for this?

**Comment by pipermerriam** [comment]
I'm :-1: on this but I'm not sure how much my opinion should matter.

My have a very long history writing python.  I really like the indentation approach for scoping.  I understand that it results in added complexity at the parsing layer.  The argument here seems to be that we should add curly braces so that supporting certain language features like multi-line lambdas is easier.  From my perspective this is adding a curly brace *tax* to all code written in this language in order for the parser to have an easier time supporting multi-line lambdas.  This cost feels high to me since it is unclear what the actual value will be in having multi-line lambdas.  The other *benefit* seems to be a simpler parser, but it sounds like it should be possible to do indentation based parsing in a sane way, and that if we take a more opinionated stance on tabs vs spaces it might be easier to do.

Language design isn't my area of specialty so my focus here is on the UX in writing the code and how adding curly braces would effect that.

**Comment by cburgdorf** [comment]
>can you provide a citation for this?

Yep, Guido van Rossum [mentioned it here](https://www.artima.com/weblogs/viewpost.jsp?thread=147358)

>But the complexity of any proposed solution for this puzzle is immense, to me: it requires the parser (or more precisely, the lexer) to be able to switch back and forth between indent-sensitive and indent-insensitive modes, keeping a stack of previous modes and indentation level. Technically that can all be solved (there's already a stack of indentation levels that could be generalized). But none of that takes away my gut feeling that it is all an elaborate Rube Goldberg contraption.

**Comment by cburgdorf** [comment]
Not trying to push this forward (we are going with Pythonic indents for now) but I accidentally came across a FAQ in the rust docs about why they decided to not use Pythonic indents and wanted [to link it here](https://prev.rust-lang.org/en-US/faq.html#why-curly-brackets).
