### ISSUE TITLE
tried to get the static encoding size of dynamically sized value at compiler/src/yul/runtime/functions/contracts.rs:67:26

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#321]
Compiling this file:

```
contract C:
 pub def r(t:address,n:u256)->bool:return false
contract r:
 pub def g()->string100:return string100("")
```

```
thread 'main' panicked at 'failed to get the static encoding size: "tried to get the static encoding size of dynamically sized value"', compiler/src/yul/runtime/functions/contracts.rs:67:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/core/src/option.rs:1300:5
   3: fe_compiler::yul::runtime::functions::contracts::calls::{{closure}}
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   6: fe_compiler::yul::runtime::functions::contracts::calls
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: fe_compiler::yul::runtime::build
  10: fe_compiler::yul::runtime::build_with_abi_dispatcher
  11: fe_compiler::yul::mappers::contracts::contract_def
  12: fe_compiler::yul::mappers::module::module
  13: fe_compiler::yul::compile
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by cburgdorf** [comment]
I looked into this today and the example can be reduced to something like this:

```
contract Other:
  foo: u8

contract Foo:
  pub def get_ticker_symbol()->string3:
    return "ETH"
```

I tried to follow down the rabbit whole and will dump here what I found in the hope that @g-r-a-n-t can shed more light on what needs to be done here :)

1. The problem is with the string encoding in the ABI but it only leads to a crash as soon as we create a second contract (here `Other`. In other words, this compiles just fine:

```
contract Foo:
  pub def get_ticker_symbol()->string3:
    return "ETH"
```

2. It is crashing because the `abi_type` for `FeString` is

https://github.com/ethereum/fe/blob/895b9b56a7b4e0821805b49dad1ea24395da5721/analyzer/src/namespace/types.rs#L758-L768

And when we generate the runtime code we call 

https://github.com/ethereum/fe/blob/895b9b56a7b4e0821805b49dad1ea24395da5721/compiler/src/yul/runtime/functions/contracts.rs#L66

which ultimatively panics because it is not meant to retrieve the size for a dynaically sized item.

https://github.com/ethereum/fe/blob/895b9b56a7b4e0821805b49dad1ea24395da5721/compiler/src/yul/operations/abi.rs#L81-L83

The initial question that came to my mind was: Why do we have a test that proves we can call a public function that returns a static string then?

https://github.com/ethereum/fe/blob/895b9b56a7b4e0821805b49dad1ea24395da5721/compiler/tests/features.rs#L559-L564

Everything around the ABI is still a bit foggy to me but my current conclusion is that the above test works fine because the data is encoded correctly and the testing code that calls the contract knows how to decode it but in the case with two contracts where contract B calls contract A *we need* to inject the decoding code into contract B and that is something that we just haven't done yet.

@g-r-a-n-t Is my base assumption correct. Do you have some thoughts to share here?

**Comment by g-r-a-n-t** [comment]
Yes, this is on the right track.

It boils down to the fact that we don't know how much memory will be used in the call return for dynamically sized types. It's not necessarily a bug, just a missing feature that is not handled well.

`call(g, a, v, in, insize, out, outsize)`

> call contract at address a with input mem[in…(in+insize)) providing g gas and v wei and output area mem[out…(out+outsize)) returning 0 on error (eg. out of gas) and 1 on success

See the Yul [docs](https://docs.soliditylang.org/en/latest/yul.html#evm-dialect).

I see two possible solutions:
1. We add a `max_size` value to `AbiType` and use that instead of this `static_encode_size` function. We of course know the max size of `string3`, since the type is bounded. One drawback to this is that we'll have trouble dealing with external contracts imported using their JSON ABIs, since dynamically sized types have no bounds there. It would definitely work in the short-term, tho.
2. We set a very high `outsize` and then only allocate what's used. I'm not quite sure if `outsize` influences memory access gas costs :thinking:.

I think for now we should just go with (1), since importing external contracts using their json ABIs is not happening anytime soon.
