### ISSUE TITLE
Short circuited behavior of if-else, and, or

### ISSUE THREAD

**Issue by formalize** [ethereum/fe#488]
### What is wrong?

The ternary if-else operator evaluates both branches and discards one of the two results, but it shouldn't evaluate the wrong branch at all. Moreover, the logical 'and' and 'or' operators are usually expected to behave like if-elses ("short circuited") rather than like bitwise operators.

For example, this Python program never calls f():

```python
def f() -> bool:
    return True

False and f()
True or f()
f() if False else False
False if True else f()
```

But this corresponding Fe program, as currently implemented, calls f() all 4 times:

```python
contract ShortCircuit:
    def f() -> bool:
        return true

    pub def main():
        false and self.f()
        true or self.f()
        self.f() if false else false
        false if true else self.f()
```

### How can it be fixed

Unfortunately there's no way to neatly compile Fe expressions into Yul expressions. Temporary variables and switch statements must be used, and those switch statements cannot be tucked inside a ternary() function as they are now.

**Comment by cburgdorf** [comment]
Ran into this today again and added the *beta-required*  flag. Looking into it.

**Comment by cburgdorf** [comment]
Ok, so far, we've always tried to stricly map expressions to expressions and statements to statements at both the lowering and the yulgen pass. It seems like we can not continue this pattern here because the only way to do so is to do what we do now and call `ternary(test, if_branch, else_branch)` but this causes all function arguments to be evaluated which prevents us from short circuting.

I propose that we tackle this at the lowering pass instead of the yulgen pass and that we turn a single ternary expression into a bigger code block as demonstrated with the following example:

Before lowering:

```
fn foo():
  some_fn(1 if some_condition else bar())
```

After lowering:

```
fn foo():
  let result: u256
  if some_condition:
    result = 1
  else:
    result = bar()
  some_fn(result)
```

This is more complex as it breaks with typical expression -> expression mapping convention but I don't see away around it.

**Comment by sbillig** [comment]
Yeah, I think this is a good approach to take. In my opinion, we should, over time, move more and more of the complexity out of the yulgen phase into some earlier phase, either our current lowering phase or some imaginary future phase involving an intermediate representation that then requires only a very simple translation into yul.
