### ISSUE TITLE
declaration of event more similar than emiting an event

### ISSUE THREAD

**Issue by sergiokessler** [ethereum/fe#565]
### What is wrong?

declaring an event is somewhat different than emitting an event

```
    # declaration now
    event Signed:
        book_msg: String<100>
...
    emit Signed(book_msg=book_msg)

```
### How can it be fixed

declaring/emiting being more similar:

```
    # declaration alternative
    event Signed(book_msg: String<100>)
...
    emit Signed(book_msg=book_msg)

```

**Comment by sbillig** [comment]
We also have (soft) plans to use a colon instead of an equal sign when constructing an event or struct. Example:

```
event Foo:
  val: u256
  bar: u256

fn f(mut ctx: Context):
   ctx.emit(Foo(val: 4711, bar: 12))
```
(mentioned here: #397)

We are using curly braces in the new `use` (import) syntax, fwiw:
```
use std::crypto::{ keccak256, bls }
```
I'm not personally opposed to doing the same in cases like event and struct construction (as we inch closer and closer to rust syntax...)

Anyway, I'm going to close this for now in the interest of tidying up our issue backlog, as we don't currently plan to change the event syntax. If we decide to revisit this, we can reopen, or open a new issue with the new proposal. Thanks for the suggestion @sergiokessler.
