### ISSUE TITLE
Setup pre-commit for project

### ISSUE THREAD

**Issue by vuvoth** [ethereum/fe#735]
### What is wrong?
We need run clippy and fmt before commit or push. I think better we should setup `pre-commit` to automatic those tasks.

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by sbillig** [comment]
I'd prefer that we not commit such a hook to the repo, at least not in a way that makes it enabled by default.

My typical workflow (for a change that will take a while) is to regularly commit and push my work-in-progress code, which is usually a hot mess that fails all tests and likely won't even compile. I do this so that my work doesn't disappear if my laptop does, and so that the world knows I'm doing things. Then when I've finished the changes and made all the tests pass, I'll do an interactive rebase to squash things together and force push to rewrite history.

Judging by past PRs, Grant and Yoshi do something similar. Christoph presumably never writes flawed code and, being German, likely has the strictest of controls already in place for himself.

**Comment by vuvoth** [comment]
> I'd prefer that we not commit such a hook to the repo, at least not in a way that makes it enabled by default.

Ah! Make sense. However, I think we can still config project use pre-commit. We can turn off it by default. People want use it can turn on it(Uhm... I not sure 100 percent but I think we can do it).
