### ISSUE TITLE
revert, emit and potentially others should be turned into library functions

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/fe#98]
This is just a quick brain dump and not actionable but I think once we are further along with our plans for a standard library then `revert` and `emit` should turn into library functions.

### Motivation

The main motivation would be to not pollute the global namespace with special keywords or built-in functions too much.

### Details

E.g. instead of:

```
type BookMsg = bytes[100]

contract GuestBook:
    pub guest_book: map<address, BookMsg>

    event Signed:
        idx book_msg: BookMsg

    pub def sign(book_msg: BookMsg):
        self.guest_book[msg.sender] = book_msg

        emit Signed(book_msg=book_msg)

    pub def get_msg(addr: address) -> BookMsg:
        return self.guest_book[addr]
```

We could have:

```
from std.evm import emit

type BookMsg = bytes[100]

contract GuestBook:
    pub guest_book: map<address, BookMsg>

    event Signed:
        idx book_msg: BookMsg

    pub def sign(book_msg: BookMsg):
        self.guest_book[msg.sender] = book_msg

        emit(Signed(book_msg=book_msg))

    pub def get_msg(addr: address) -> BookMsg:
        return self.guest_book[addr]
```

**Comment by g-r-a-n-t** [comment]
I think this would be a good place to start on the standard library.

We may want to consider adding an [unsafe](https://doc.rust-lang.org/nomicon/what-unsafe-does.html) feature to Fe so that these functions can actually be implemented. I imagine this is part of the reason why Rust introduced it in the first place, because they wanted to prioritized library-features while also providing safety through limitation.

**Comment by cburgdorf** [comment]
>We may want to consider adding an unsafe feature to Fe so that these functions can actually be implemented.

Can you elaborate on the need for `unsafe` here?
The simplest way I can think of to implement that would be to just map the import of e.g `revert` to a YUL function `revert` that we would generate which would roughly look like:

```
function revert() {
    revert(0, 0)
}
```

**Comment by g-r-a-n-t** [comment]
> Can you elaborate on the need for unsafe here?

Yeah, so I was thinking that we would try to implement `revert` and other std lib features in actual Fe modules. And if we were to do this, we would need to provide a bit more flexibility in the language. The problem with this, though, is that providing more flexibility can be at odds with safety. In the case of `revert`, implementing it in Fe would require us to use some sort of Yul code block:

```python
pub def revert():
  yul:
    revert(0, 0)
```  

The issue with allowing users to define Yul code blocks is that they can easily break their program, for example:

```python
pub def revert():
  yul:
    mstore(26, 42) # overwrite some value stored in memory
``` 

In Rust, you would first need to enter unsafe mode to do this (see [inline assembly](https://doc.rust-lang.org/1.8.0/book/inline-assembly.html)). So we could have something like this:

```python
pub def revert():
  unsafe:
    yul:
      revert(0, 0)
``` 

*I realize the syntax given here doesn't look great*

Of course, you can still write Yul in this unsafe block that breaks your program, but you're at least required to acknowledge that the code you're writing is unsafe and more scrutiny should be applied. I like this approach because it makes it easy for someone to write code with basic safety guarantees, while also allowing people to break the rules on occasions where it's required.

**Comment by cburgdorf** [comment]
While I generally still agree that long term we should move certain things into a planned std library I have changed my view regarding `revert` and `emit` and think they might be better off staying keywords. I've put down a few more words on `revert` [here](https://github.com/ethereum/fe/issues/75#issuecomment-824750525). I'm closing this issue for now.
